

export const GET_ENROLLED_COURSE = "GET_ENROLLED_COURSE";

export const GET_ENROLLED_COURSE_DATA = "GET_ENROLLED_COURSE_DATA";

export const GET_ENROLLED_COURSE_API_ERROR = "GET_ENROLLED_COURSE_API_ERROR";


export const GET_ONBOARDING_DATA = "GET_ONBOARDING_COURSE_DATA";
