export const GET_ALL_COURSE_SESSIONS = "GET_ALL_COURSE_SESSIONS";
export const GET_ONE_COURSE_SESSIONS = "GET_ONE_COURSE_SESSIONS";
export const POST_ASSIGNMENT = "POST_ASSIGNMENT";
export const GET_CARTIFICATE_ID = "GET_CARTIFICATE_ID";
export const GET_ASSIGNMENT = "GET_ASSIGNMENT";
export const FLUSH_ASSIGNMENT = "FLUSH_ASSIGNMENT";
export const GET_COMMENTS = "GET_COMMENTS";
export const SESSION_LOAD = "SESSION_LOAD";
export const SESSION_ERROR = "SESSION_ERROR";

export const CMNT_IDX = "CMNT_IDX";
export const LOADER_COURSEMAT = "LOADER_COURSEMAT";