export const GET_ALL_ASSIGNED_COURSE = "GET_ALL_ASSIGNED_COURSE";
export const GET_ONBOARDING_DATA = "GET_ONBOARDING_COURSE_DATA";
export const GET_ALL_SESSIONS = "GET_ALL_SESSIONS";
export const GET_SESSION_DETAILS = "GET_SESSION_DETAILS";
export const GET_ALL_ASSIGNED_COURSE_ERROR = "GET_ALL_ASSIGNED_COURSE_ERROR";

export const GET_MENTOR_DATA = "GET_MENTOR_DATA";

export const GET_ENROLLED_COURSE = "GET_ENROLLED_COURSE";

