export const GET_DATA_REQ = "GET_DATA_REQ";

export const GET_DETAUX_HOME_SUCCESS = "GET_DETAUX_HOME_SUCCESS";
export const GET_DETAUX_API_FAIL = "GET_DETAUX_HOME_FAIL";

export const GET_MEETUPS_SUCCESS = "GET_MEETUPS_SUCCESS";

export const GET_MEETUP_SUCCESS = "GET_MEETUP_SUCCESS";

export const GET_PUBLICATIONS_SUCCESS = "GET_PUBLICATIONS_SUCCESS";




