export const GET_WEEK_DATA = "GET_WEEK_DATA";
export const GET_FILTER_DATA = "GET_FILTER_DATA";
export const REMOVE_DATA = "REMOVE_DATA";
export const GET_EFFORT_DATA = "GET_EFFORT_DATA";
export const GET_MENROT_PANDING_ASSINMENT = "GET_MENROT_PANDING_ASSINMENT"