export const GET_PORTFOLIO = "GET_PORTFOLIO";

export const GET_PORTFOLIO_DATA = "GET_PORTFOLIO_DATA";

export const GET_PORTFOLIO_API_ERROR = "GET_PORTFOLIO_API_ERROR";
export const GET_MEDIUM_DATA = "GET_MEDIUM_DATA";

export const GET_GLOBAL_DATA = "GET_GLOBAL_DATA";

export const GETALL_CASE_STUDIES = "GETALL_CASE_STUDIES";