export const GET_COURSE_DETAILS_LOAD = "GET_COURSE_DETAILS_LOAD";

export const GET_COURSE_DETAILS_DATA = "GET_COURSE_DETAILS_DATA";

export const GET_COURSE_DETAILS_FOR_UPDATE_DATA =
  "GET_COURSE_DETAILS_FOR_UPDATE_DATA";

export const GET_COURSE_DETAILS_DATA_API_ERROR =
  "GET_COURSE_DETAILS_DATA_API_ERROR";

export const CREATE_BATCH_API_ERROR = "CREATE_BATCH_API_ERROR";

export const DELETE_GET_COURSE_DETAILS_DATA = "DELETE_GET_COURSE_DETAILS_DATA";
export const GET_BATCH_ERROR = "GET_BATCH_ERROR";

export const GET_OVERVIEW_DATA = "GET_OVERVIEW_DATA";
export const GET_HIGHLIGHTS_DATA = "GET_HIGHLIGHTS_DATA";
export const GET_OUTCOMES_DATA = "GET_OUTCOMES_DATA";
export const GET_BENEFITS_DATA = "GET_BENEFITS_DATA";
export const GET_PLAN_DATA = "GET_PLAN_DATA";
export const GET_MODULES_DATA = "GET_MODULES_DATA";
export const GET_ELIGIBILTY_DATA = "GET_ELIGIBILTY_DATA";
export const GET_CAREERPROSPECTS_DATA = "GET_CAREERPROSPECTS_DATA";
export const GET_MENTORS_DATA = "GET_MENTORS_DATA";
export const GET_TESTIMONIALS_DATA = "GET_TESTIMONIALS_DATA";

export const WEB_STATUS = "WEB_STATUS";
export const WEB_URL = "WEB_URL";

export const ADD_MODULES = "ADD_MODULES";
export const STORE_MODULES = "STORE_MODULES";
export const REMOVE_MODULE_THUMBNAIL = "REMOVE_MODULE_THUMBNAIL";

export const EMPTY_COURSE_DETAILS = "EMPTY_COURSE_DETAILS";

export const SEND_LOAD = "SEND_LOAD";
export const FILTER_COURSE = "FILTER_COURSE";
export const FLUSH_COURSE = "FLUSH_COURSE";





